### ISSUE TITLE
Paths for Netherlands charts have changed

### ISSUE THREAD

**Issue by gitter271** [chartcatalogs/catalogs#17]
OpenCPN uses this file to fetch the ECN charts for the Netherlands:
https://raw.githubusercontent.com/chartcatalogs/catalogs/master/NL_IENC_Catalog.xml

In it there are some links that have moved.

The correct links can be found here:
https://www.vaarweginformatie.nl/frp/main/#/page/infra_enc

Or get them here:

Zeeland Compleet Week 4 - 2020 – 385 MB - 21-01-2020
https://www.vaarweginformatie.nl/fdd/main/wicket/resource/org.apache.wicket.Application/downloadfileResource?fileId=2533282938

Rotterdam 2019-11-22
https://www.vaarweginformatie.nl/fdd/main/wicket/resource/org.apache.wicket.Application/downloadfileResource?fileId=2491882897

Nederland (nog te vervangen) met kaart 2019-08-07 - 6MB
https://www.vaarweginformatie.nl/fdd/main/wicket/resource/org.apache.wicket.Application/downloadfileResource?fileId=2431638959

Nederland (nieuwe publicatie) met kaart 2019-08-07 - 43MB
https://www.vaarweginformatie.nl/fdd/main/wicket/resource/org.apache.wicket.Application/downloadfileResource?fileId=2431638625

IENC Haven Geertruidenberg - 22-02-2017
https://www.vaarweginformatie.nl/fdd/main/wicket/resource/org.apache.wicket.Application/downloadfileResource?fileId=161337079

IENC Haven Waspik - 01-06-2016
https://www.vaarweginformatie.nl/fdd/main/wicket/resource/org.apache.wicket.Application/downloadfileResource?fileId=113616371

Also there's a typo:
Netherland Inland ENC Charts => Netherlands Inland ENC Charts

**Comment by nohal** [comment]
Automatic updates are in place now.
