### ISSUE TITLE
FR_IENC_Catalog path changed

### ISSUE THREAD

**Issue by ozolli** [chartcatalogs/catalogs#27]
Hello,
The new path is https://www.vnf.fr/vnf/app/uploads/ecdis/data/ instead of http://www.vnf.fr/ecdis/data/

**Comment by nohal** [comment]
Really no TLS? Sorry I'm asking, but vnf.fr is not accessible at all from where I and my servers are...

**Comment by ozolli** [comment]
vnf.fr has been badly hacked last year and still doesn't allow connections from a lot of countries. I'm French so I can access all the resources.
I believe they automatically rewrite http to https, so http://www.vnf.fr/vnf/app/uploads/ecdis/data/ is technically okay but TLS seems enforced.

**Comment by nohal** [comment]
Please try to confirm the URLs work now, I have no way to do so...

**Comment by ozolli** [comment]
Yes it works fine, thank you !
