### ISSUE TITLE
Brazilian Chart Table

### ISSUE THREAD

**Issue by Skippern** [chartcatalogs/catalogs#6]
The HTML Table for Brazilian charts have been moved to the following address, lots of charts in process of updating....

RNC: http://www.mar.mil.br/dhn/chm/box-cartas-raster/raster_disponiveis.html
ENC: http://www.mar.mil.br/dhn/bhmn/cartasenc1.html

Hope this is helpful - consider this as "for info"

**Comment by PovlAbrahamsen** [comment]
I've started to update the RNC chart catalog. I've just submitted a push request covering all charts except 3361-3400 and 3417-3442. I'll try to do the remaining charts sometime in the next week!

**Comment by Skippern** [comment]
ENC have moved to http://www.mar.mil.br/dhn/bhmn/enc.html

**Comment by nohal** [comment]
Did I miss something? Are the files downloadable from that page charts at all? It seems like the page only contains links to the 2 VARs and permits and chart folio updates for different vessels, useless for anybody else.

**Comment by Skippern** [comment]
I need to check that when I can sit down with my chart software

**Comment by nohal** [comment]
I take it they are S63 and useless for us.
